# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clilol < Formula
  desc "A CLI for omg.lol"
  homepage "https://mcornick.com/clilol"
  version "0.1.0"
  license "MIT"

  on_macos do
    url "https://github.com/mcornick/clilol/releases/download/v0.1.0/clilol_0.1.0_darwin_all.tar.gz"
    sha256 "88cee5d43e8204aeb609a7a8e59fe643a089d6b01d21080d94886de1fabb8842"

    def install
      bin.install "clilol"
      bash_completion.install "completions/clilol.bash" => "clilol"
      zsh_completion.install "completions/clilol.zsh" => "_clilol"
      fish_completion.install "completions/clilol.fish"
      man1.install "manpages/*.1"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/mcornick/clilol/releases/download/v0.1.0/clilol_0.1.0_linux_armv6.tar.gz"
      sha256 "da635fa01a4eaa5fd129c519d42e23dd4fb43ca21699c0489f273612d0aedc06"

      def install
        bin.install "clilol"
        bash_completion.install "completions/clilol.bash" => "clilol"
        zsh_completion.install "completions/clilol.zsh" => "_clilol"
        fish_completion.install "completions/clilol.fish"
        man1.install "manpages/*.1"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mcornick/clilol/releases/download/v0.1.0/clilol_0.1.0_linux_amd64.tar.gz"
      sha256 "6c6f7195edc7113f01dce920310f05cda16687565ea9d055919faad3e7b6cc72"

      def install
        bin.install "clilol"
        bash_completion.install "completions/clilol.bash" => "clilol"
        zsh_completion.install "completions/clilol.zsh" => "_clilol"
        fish_completion.install "completions/clilol.fish"
        man1.install "manpages/*.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mcornick/clilol/releases/download/v0.1.0/clilol_0.1.0_linux_arm64.tar.gz"
      sha256 "dcd560572641ea98592796874aecb043914fa4fe616451cc62004ebe44d2ba92"

      def install
        bin.install "clilol"
        bash_completion.install "completions/clilol.bash" => "clilol"
        zsh_completion.install "completions/clilol.zsh" => "_clilol"
        fish_completion.install "completions/clilol.fish"
        man1.install "manpages/*.1"
      end
    end
  end
end
