# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clilol < Formula
  desc "A CLI for omg.lol"
  homepage "https://clilol.readthedocs.io/"
  version "1.0.18"
  license "MPL-2.0"

  on_macos do
    url "https://github.com/mcornick/clilol/releases/download/v1.0.18/clilol_1.0.18_darwin_all.tar.gz"
    sha256 "bc67b1b1065bfa36e895bc3408c7618a6f8355bce04b1f29fdc2052c4e0f5876"

    def install
      bin.install "clilol"
      bash_completion.install "completions/clilol.bash" => "clilol"
      zsh_completion.install "completions/clilol.zsh" => "_clilol"
      fish_completion.install "completions/clilol.fish"
      man1.install Dir["manpages/*.1"]
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mcornick/clilol/releases/download/v1.0.18/clilol_1.0.18_linux_amd64.tar.gz"
        sha256 "fecb4789842d88e989b66dd91cdec1ba4df562439a17e0e6512fac96cdadf6d1"

        def install
          bin.install "clilol"
          bash_completion.install "completions/clilol.bash" => "clilol"
          zsh_completion.install "completions/clilol.zsh" => "_clilol"
          fish_completion.install "completions/clilol.fish"
          man1.install Dir["manpages/*.1"]
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/mcornick/clilol/releases/download/v1.0.18/clilol_1.0.18_linux_armv6.tar.gz"
        sha256 "df53ab05fcf92c025eda6112726d8983843492c0573589ebffe5820bfb52636b"

        def install
          bin.install "clilol"
          bash_completion.install "completions/clilol.bash" => "clilol"
          zsh_completion.install "completions/clilol.zsh" => "_clilol"
          fish_completion.install "completions/clilol.fish"
          man1.install Dir["manpages/*.1"]
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mcornick/clilol/releases/download/v1.0.18/clilol_1.0.18_linux_arm64.tar.gz"
        sha256 "886b9d0cb7f93bc820d302a064794292baae139ed3b40a98039fe588e7986c2c"

        def install
          bin.install "clilol"
          bash_completion.install "completions/clilol.bash" => "clilol"
          zsh_completion.install "completions/clilol.zsh" => "_clilol"
          fish_completion.install "completions/clilol.fish"
          man1.install Dir["manpages/*.1"]
        end
      end
    end
  end
end
