# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Genpw < Formula
  desc "Generates strings that can be used as reasonably secure passwords."
  homepage "https://github.com/markcornick/genpw"
  version "3.0.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/markcornick/genpw/releases/download/v3.0.0/genpw_3.0.0_Darwin_x86_64.tar.gz"
      sha256 "96032c353f83c971da109fa65e8d8c148ee5ccaaaf9f4b09ecd6ed17591e3aac"
    end
    if Hardware::CPU.arm?
      url "https://github.com/markcornick/genpw/releases/download/v3.0.0/genpw_3.0.0_Darwin_arm64.tar.gz"
      sha256 "ffd3e8e8cac58d12720231d428a7abbf08d2b6d124bbf74ed278f02667d1ff8b"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/markcornick/genpw/releases/download/v3.0.0/genpw_3.0.0_Linux_x86_64.tar.gz"
      sha256 "850ca30ff157cf51e19c3da8cf648c7bf562e3cf9c21f84c0e8c2da55cf19a28"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/markcornick/genpw/releases/download/v3.0.0/genpw_3.0.0_Linux_armv6.tar.gz"
      sha256 "57b85c9b3312a4b5b86150e37115013e0962cd3e393314e8bb80bed17b6ae5d5"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/markcornick/genpw/releases/download/v3.0.0/genpw_3.0.0_Linux_arm64.tar.gz"
      sha256 "ce04551fbb8bd8164103d8d9d15afb7027b0f89566a2008e60f4de7798dfb9b9"
    end
  end

  def install
    bin.install "genpw"
  end
end
