# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Genpw < Formula
  desc "Generates strings that can be used as reasonably secure passwords."
  homepage "https://github.com/markcornick/genpw"
  version "4.0.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/markcornick/genpw/releases/download/v4.0.0/genpw_4.0.0_Darwin_x86_64.tar.gz"
      sha256 "975f60a7817362c4342d908f7f313959d08daed22146c997beb29455c97f8a64"
    end
    if Hardware::CPU.arm?
      url "https://github.com/markcornick/genpw/releases/download/v4.0.0/genpw_4.0.0_Darwin_arm64.tar.gz"
      sha256 "f9cb812e4c0904464b932e1e346ee0b6ff7bb4e7e58598bddc601b37b6b2e111"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/markcornick/genpw/releases/download/v4.0.0/genpw_4.0.0_Linux_x86_64.tar.gz"
      sha256 "ba9e8584985f2789e92636291745c9d48461ecae16030f3cdf16e508793639a1"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/markcornick/genpw/releases/download/v4.0.0/genpw_4.0.0_Linux_armv6.tar.gz"
      sha256 "b91dc32326cd9e208355d97be5e6bfe01d107ad25a589f0568bf88dc7c962522"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/markcornick/genpw/releases/download/v4.0.0/genpw_4.0.0_Linux_arm64.tar.gz"
      sha256 "bea1c4080a2f26c0dc7279562e5435832949f302d155f3fa617c10d6ba5476d9"
    end
  end

  def install
    bin.install "genpw"
  end
end
