# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LinenoiseClassic < Formula
  desc "Generates strings that can be used as reasonably secure passwords."
  homepage "https://github.com/markcornick/linenoise-classic"
  version "1.0.3"

  on_macos do
    url "https://github.com/markcornick/linenoise-classic/releases/download/v1.0.3/linenoise-classic_1.0.3_darwin_all.tar.gz"
    sha256 "bd1ec801e3fa903ea5e04d81b8cad54d6bc05754834bdb0f47f26fb820317134"

    def install
      bin.install "linenoise-classic"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/markcornick/linenoise-classic/releases/download/v1.0.3/linenoise-classic_1.0.3_linux_amd64.tar.gz"
      sha256 "6a7f5fd9d1382acb91ee115846b5fc6e1687241278145c16e735f75c9d4a3f06"

      def install
        bin.install "linenoise-classic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/markcornick/linenoise-classic/releases/download/v1.0.3/linenoise-classic_1.0.3_linux_arm64.tar.gz"
      sha256 "297507379d07f96ea55ac1d6040012ef54357fee5338b3d9366f0a106cd869c1"

      def install
        bin.install "linenoise-classic"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/markcornick/linenoise-classic/releases/download/v1.0.3/linenoise-classic_1.0.3_linux_armv6.tar.gz"
      sha256 "0bee8da704427c050418ecdf748f9b067c81635f15464db7c8d6e710c23437df"

      def install
        bin.install "linenoise-classic"
      end
    end
  end
end
