# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LinenoiseClassic < Formula
  desc "Generates strings that can be used as reasonably secure passwords."
  homepage "https://github.com/markcornick/linenoise-classic"
  version "1.0.1"

  on_macos do
    url "https://github.com/markcornick/linenoise-classic/releases/download/v1.0.1/linenoise-classic_1.0.1_darwin_all.tar.gz"
    sha256 "ab82c28ec09d3e5bc38828c57275ae6d644cd7479c61731496077ac151d71c46"

    def install
      bin.install "linenoise-classic"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/markcornick/linenoise-classic/releases/download/v1.0.1/linenoise-classic_1.0.1_linux_armv6.tar.gz"
      sha256 "503a5d29ed0b549cd8f9e0bdaf30202918f601cbefd2e00659f6c646948b142f"

      def install
        bin.install "linenoise-classic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/markcornick/linenoise-classic/releases/download/v1.0.1/linenoise-classic_1.0.1_linux_arm64.tar.gz"
      sha256 "003a546268d0fcb72a21c5850b3eaf4fd1b954bffcab847c5e356efbd63ac75c"

      def install
        bin.install "linenoise-classic"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/markcornick/linenoise-classic/releases/download/v1.0.1/linenoise-classic_1.0.1_linux_amd64.tar.gz"
      sha256 "412f22f115a38ce8aa0946fe265e72bd31e97dcf75078b2365c7e0d41501a99c"

      def install
        bin.install "linenoise-classic"
      end
    end
  end
end
