# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LinenoiseCli < Formula
  desc "Generates strings that can be used as reasonably secure passwords."
  homepage "https://github.com/mcornick/linenoise-cli"
  version "1.1.2"

  on_macos do
    url "https://github.com/mcornick/linenoise-cli/releases/download/v1.1.2/linenoise-cli_1.1.2_darwin_all.tar.gz"
    sha256 "100f62c8b1d494cab5bf8ad5901c034202e2ddcab87d97dc86e4bb37141d7b7f"

    def install
      bin.install "linenoise-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mcornick/linenoise-cli/releases/download/v1.1.2/linenoise-cli_1.1.2_linux_arm64.tar.gz"
      sha256 "7cb3a02a8ec319c1fce4847f84f603547ed646df0fad25c8a0d41555d590d11b"

      def install
        bin.install "linenoise-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mcornick/linenoise-cli/releases/download/v1.1.2/linenoise-cli_1.1.2_linux_amd64.tar.gz"
      sha256 "f801b1ee0cdeb97f5b20a46ca2d69e836f4f73412005c4271b6bac8f954cfcfd"

      def install
        bin.install "linenoise-cli"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/mcornick/linenoise-cli/releases/download/v1.1.2/linenoise-cli_1.1.2_linux_armv6.tar.gz"
      sha256 "048bd9be1edcbd9200273d21b7a5063b3c6aaa2f7ec0ef7fdb46eb047d8869a0"

      def install
        bin.install "linenoise-cli"
      end
    end
  end
end
