# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LinenoiseCli < Formula
  desc "Generates strings that can be used as reasonably secure passwords."
  homepage "https://github.com/mcornick/linenoise-cli"
  version "1.1.3"

  on_macos do
    url "https://github.com/mcornick/linenoise-cli/releases/download/v1.1.3/linenoise-cli_1.1.3_darwin_all.tar.gz"
    sha256 "0ec31252606060b436c5f4042f45146f8c14f3fc37b8101002036c364f9f28a6"

    def install
      bin.install "linenoise-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/mcornick/linenoise-cli/releases/download/v1.1.3/linenoise-cli_1.1.3_linux_armv6.tar.gz"
      sha256 "9796a96c6e9848f099926b726b5187fb6e51cc8e69b015897e3da25b6d224abe"

      def install
        bin.install "linenoise-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mcornick/linenoise-cli/releases/download/v1.1.3/linenoise-cli_1.1.3_linux_amd64.tar.gz"
      sha256 "d6b8158d6eb8f1b27a3680b8312108072cacb722ce6703c867b82a03eb9f3c31"

      def install
        bin.install "linenoise-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mcornick/linenoise-cli/releases/download/v1.1.3/linenoise-cli_1.1.3_linux_arm64.tar.gz"
      sha256 "4317021ecd4e23b1f07fb5acb96fe4ae412187089d6d92a048e6eb864cc8d76e"

      def install
        bin.install "linenoise-cli"
      end
    end
  end
end
