# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mpg < Formula
  desc "Mark's Password Generator"
  homepage "https://github.com/mcornick/mpg"
  version "1.0.35"
  license "MIT"

  on_macos do
    url "https://github.com/mcornick/mpg/releases/download/v1.0.35/mpg_1.0.35_darwin_all.tar.gz"
    sha256 "e7c6805c78b593f24093e8bead163d944fc94dd901b30cd5cde2879878a6f3b2"

    def install
      bin.install "mpg"
      bash_completion.install "completions/mpg.bash" => "mpg"
      zsh_completion.install "completions/mpg.zsh" => "_mpg"
      fish_completion.install "completions/mpg.fish"
      man1.install "manpages/mpg.1"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/mcornick/mpg/releases/download/v1.0.35/mpg_1.0.35_linux_armv6.tar.gz"
      sha256 "3fb92e0bfdeb2fc81e4aa79bb20bce739fe946001edf3185c97d50e146053684"

      def install
        bin.install "mpg"
        bash_completion.install "completions/mpg.bash" => "mpg"
        zsh_completion.install "completions/mpg.zsh" => "_mpg"
        fish_completion.install "completions/mpg.fish"
        man1.install "manpages/mpg.1"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mcornick/mpg/releases/download/v1.0.35/mpg_1.0.35_linux_amd64.tar.gz"
      sha256 "9a92dedf7620d7aa27745976145c743201e027eeac84d781b7a55f12d5a97f25"

      def install
        bin.install "mpg"
        bash_completion.install "completions/mpg.bash" => "mpg"
        zsh_completion.install "completions/mpg.zsh" => "_mpg"
        fish_completion.install "completions/mpg.fish"
        man1.install "manpages/mpg.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mcornick/mpg/releases/download/v1.0.35/mpg_1.0.35_linux_arm64.tar.gz"
      sha256 "4a6753009399fb3be1639edc5ce972a70847f9d03c256e90da52b53a0eb1e2fb"

      def install
        bin.install "mpg"
        bash_completion.install "completions/mpg.bash" => "mpg"
        zsh_completion.install "completions/mpg.zsh" => "_mpg"
        fish_completion.install "completions/mpg.fish"
        man1.install "manpages/mpg.1"
      end
    end
  end
end
