# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mpg < Formula
  desc "Mark's Password Generator"
  homepage "https://github.com/mcornick/mpg"
  version "1.0.32"
  license "MIT"

  on_macos do
    url "https://github.com/mcornick/mpg/releases/download/v1.0.32/mpg_1.0.32_darwin_all.tar.gz"
    sha256 "3c7fbef353aefd43d0ca8f3416805911aee9d3701410d8fcff4e3666fdc5d06b"

    def install
      bin.install "mpg"
      bash_completion.install "completions/mpg.bash" => "mpg"
      zsh_completion.install "completions/mpg.zsh" => "_mpg"
      fish_completion.install "completions/mpg.fish"
      man1.install "manpages/mpg.1"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mcornick/mpg/releases/download/v1.0.32/mpg_1.0.32_linux_amd64.tar.gz"
      sha256 "d0ca692b607e02c733909dd5b68f3e81d095223f63d753fa215ea441f7151984"

      def install
        bin.install "mpg"
        bash_completion.install "completions/mpg.bash" => "mpg"
        zsh_completion.install "completions/mpg.zsh" => "_mpg"
        fish_completion.install "completions/mpg.fish"
        man1.install "manpages/mpg.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mcornick/mpg/releases/download/v1.0.32/mpg_1.0.32_linux_arm64.tar.gz"
      sha256 "4a82a0268e8c6a234fc921e80d34996d2f90923497dbe4eca401be2cc26de871"

      def install
        bin.install "mpg"
        bash_completion.install "completions/mpg.bash" => "mpg"
        zsh_completion.install "completions/mpg.zsh" => "_mpg"
        fish_completion.install "completions/mpg.fish"
        man1.install "manpages/mpg.1"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/mcornick/mpg/releases/download/v1.0.32/mpg_1.0.32_linux_armv6.tar.gz"
      sha256 "8c74c860c151b500b7ed15d93257ec0bb183261b71c392ffef687520662a8fc8"

      def install
        bin.install "mpg"
        bash_completion.install "completions/mpg.bash" => "mpg"
        zsh_completion.install "completions/mpg.zsh" => "_mpg"
        fish_completion.install "completions/mpg.fish"
        man1.install "manpages/mpg.1"
      end
    end
  end
end
