# This file was generated by GoReleaser. DO NOT EDIT.
cask "clilol" do
  desc "A CLI for omg.lol"
  homepage "https://clilol.readthedocs.io/"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clilol"
  manpage "manpages/clilol.1"
  bash_completion "completions/clilol.bash"
  zsh_completion "completions/clilol.zsh"
  fish_completion "completions/clilol.fish"

  on_macos do
    url "https://github.com/mcornick/clilol/releases/download/v1.1.0/clilol_1.1.0_darwin_all.tar.gz"
    sha256 "a40d1d64a3b67435bde0c462af2cf6eb8cfdbbd2d7173dcaf55e615f2cde28ce"
  end

  on_linux do
    on_intel do
      url "https://github.com/mcornick/clilol/releases/download/v1.1.0/clilol_1.1.0_linux_amd64.tar.gz"
      sha256 "9110952d5fe5f4871fb5c879e0047e2f6b5a9e9ed493b659646f80f347506b65"
    end
    on_arm do
      url "https://github.com/mcornick/clilol/releases/download/v1.1.0/clilol_1.1.0_linux_arm64.tar.gz"
      sha256 "35a37f597132d91164f3e2a0bdfe006b10a592542fea7bda571f18954bbd3611"
    end
  end

  conflicts_with formula: [
      "clilol",
    ]

  # No zap stanza required
end
