# This file was generated by GoReleaser. DO NOT EDIT.
cask "clilol" do
  desc "A CLI for omg.lol"
  homepage "https://clilol.readthedocs.io/"
  version "1.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clilol"
  manpage "manpages/clilol.1"
  bash_completion "completions/clilol.bash"
  zsh_completion "completions/clilol.zsh"
  fish_completion "completions/clilol.fish"

  on_macos do
    url "https://github.com/mcornick/clilol/releases/download/v1.1.2/clilol_1.1.2_darwin_all.tar.gz"
    sha256 "3039f3ffd7081c9ff10c5d982c71271b89f01b97083a3352bcd92b3c2680b582"
  end

  on_linux do
    on_intel do
      url "https://github.com/mcornick/clilol/releases/download/v1.1.2/clilol_1.1.2_linux_amd64.tar.gz"
      sha256 "0ef1899d614b90c4e308e168e8863bbb0be6cc5256d85240d6d4cd8117ab10e1"
    end
    on_arm do
      url "https://github.com/mcornick/clilol/releases/download/v1.1.2/clilol_1.1.2_linux_arm64.tar.gz"
      sha256 "aa7a5823dc92def26557ef244484ea12320655f41da8c0efd9b4e151c005a77d"
    end
  end

  conflicts_with formula: [
      "clilol",
    ]

  # No zap stanza required
end
