# This file was generated by GoReleaser. DO NOT EDIT.
cask "clilol" do
  desc "A CLI for omg.lol"
  homepage "https://clilol.readthedocs.io/"
  version "1.0.28-pre7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clilol"
  manpage "manpages/clilol.1"
  manpage "manpages/clilol-create.1"
  manpage "manpages/clilol-create-dns.1"
  manpage "manpages/clilol-create-paste.1"
  manpage "manpages/clilol-create-picture.1"
  manpage "manpages/clilol-create-purl.1"
  manpage "manpages/clilol-create-status.1"
  manpage "manpages/clilol-create-weblog.1"
  manpage "manpages/clilol-delete.1"
  manpage "manpages/clilol-delete-account.1"
  manpage "manpages/clilol-delete-account-session.1"
  manpage "manpages/clilol-delete-dns.1"
  manpage "manpages/clilol-delete-paste.1"
  manpage "manpages/clilol-delete-picture.1"
  manpage "manpages/clilol-delete-purl.1"
  manpage "manpages/clilol-delete-status.1"
  manpage "manpages/clilol-delete-weblog.1"
  manpage "manpages/clilol-get.1"
  manpage "manpages/clilol-get-account.1"
  manpage "manpages/clilol-get-account-info.1"
  manpage "manpages/clilol-get-account-name.1"
  manpage "manpages/clilol-get-account-settings.1"
  manpage "manpages/clilol-get-address.1"
  manpage "manpages/clilol-get-address-availability.1"
  manpage "manpages/clilol-get-address-expiration.1"
  manpage "manpages/clilol-get-address-info.1"
  manpage "manpages/clilol-get-dns.1"
  manpage "manpages/clilol-get-email.1"
  manpage "manpages/clilol-get-now.1"
  manpage "manpages/clilol-get-paste.1"
  manpage "manpages/clilol-get-purl.1"
  manpage "manpages/clilol-get-service.1"
  manpage "manpages/clilol-get-status.1"
  manpage "manpages/clilol-get-status-bio.1"
  manpage "manpages/clilol-get-theme.1"
  manpage "manpages/clilol-get-theme-preview.1"
  manpage "manpages/clilol-get-web.1"
  manpage "manpages/clilol-get-weblog.1"
  manpage "manpages/clilol-get-weblog-config.1"
  manpage "manpages/clilol-get-weblog-latest.1"
  manpage "manpages/clilol-get-weblog-template.1"
  manpage "manpages/clilol-list.1"
  manpage "manpages/clilol-list-account.1"
  manpage "manpages/clilol-list-account-addresses.1"
  manpage "manpages/clilol-list-account-sessions.1"
  manpage "manpages/clilol-list-directory.1"
  manpage "manpages/clilol-list-dns.1"
  manpage "manpages/clilol-list-now.1"
  manpage "manpages/clilol-list-pastes.1"
  manpage "manpages/clilol-list-pictures.1"
  manpage "manpages/clilol-list-purls.1"
  manpage "manpages/clilol-list-statuses.1"
  manpage "manpages/clilol-list-statuslog.1"
  manpage "manpages/clilol-list-themes.1"
  manpage "manpages/clilol-list-weblogs.1"
  manpage "manpages/clilol-update.1"
  manpage "manpages/clilol-update-account.1"
  manpage "manpages/clilol-update-account-name.1"
  manpage "manpages/clilol-update-account-settings.1"
  manpage "manpages/clilol-update-dns.1"
  manpage "manpages/clilol-update-email.1"
  manpage "manpages/clilol-update-now.1"
  manpage "manpages/clilol-update-preference.1"
  manpage "manpages/clilol-update-status.1"
  manpage "manpages/clilol-update-status-bio.1"
  manpage "manpages/clilol-update-web.1"
  manpage "manpages/clilol-update-weblog.1"
  manpage "manpages/clilol-update-weblog-config.1"
  manpage "manpages/clilol-update-weblog-template.1"
  manpage "manpages/clilol-update-web-pfp.1"
  bash_completion "completions/clilol.bash"
  zsh_completion "completions/clilol.zsh"
  fish_completion "completions/clilol.fish"

  on_macos do
    url "https://github.com/mcornick/clilol/releases/download/v1.0.28-pre7/clilol_1.0.28-pre7_darwin_all.tar.gz"
    sha256 "41a74b82410d19af53403c2b5c2f0b616dfda7e0a2bc588ac494332dcfd7d009"
  end

  on_linux do
    on_intel do
      url "https://github.com/mcornick/clilol/releases/download/v1.0.28-pre7/clilol_1.0.28-pre7_linux_amd64.tar.gz"
      sha256 "667da0bc10985cf1855e4605c4fc280603b1310fbff21bbc00f0b87e1afa8e41"
    end
    on_arm do
      url "https://github.com/mcornick/clilol/releases/download/v1.0.28-pre7/clilol_1.0.28-pre7_linux_arm64.tar.gz"
      sha256 "a58e2627b4a4cbabb1e720d1b366099ac37e91fd7d9d9a455d4f3b3aeeeca4cd"
    end
  end

  conflicts_with formula: [
      "clilol",
    ]

  # No zap stanza required
end
