# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LinenoiseCli < Formula
  desc "Generates strings that can be used as reasonably secure passwords"
  homepage "https://github.com/mcornick/linenoise-cli"
  version "1.2.12"
  license "MIT"

  on_macos do
    url "https://github.com/mcornick/linenoise-cli/releases/download/v1.2.12/linenoise-cli_1.2.12_darwin_all.tar.gz"
    sha256 "4947c1cab8bb00299d79e6f963284d2f8e5c20915012772047e75bce8632802b"

    def install
      bin.install "linenoise-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/mcornick/linenoise-cli/releases/download/v1.2.12/linenoise-cli_1.2.12_linux_armv7.tar.gz"
      sha256 "59699e576ade3baae49f9960fb7430787057a210dd279e8a6f589f6572b5d15e"

      def install
        bin.install "linenoise-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mcornick/linenoise-cli/releases/download/v1.2.12/linenoise-cli_1.2.12_linux_arm64.tar.gz"
      sha256 "ed18482edfeb65061598088c23f4facc1494fac1576f962b2972fed047825580"

      def install
        bin.install "linenoise-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mcornick/linenoise-cli/releases/download/v1.2.12/linenoise-cli_1.2.12_linux_amd64.tar.gz"
      sha256 "14beb3aa198437725d56c81d0577cac4ca6236fc8081ce04f01d10f4df1b2856"

      def install
        bin.install "linenoise-cli"
      end
    end
  end
end
