# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LinenoiseCli < Formula
  desc "Generates strings that can be used as reasonably secure passwords"
  homepage "https://github.com/mcornick/linenoise-cli"
  version "1.2.15"
  license "MIT"

  on_macos do
    url "https://github.com/mcornick/linenoise-cli/releases/download/v1.2.15/linenoise-cli_1.2.15_darwin_all.tar.gz"
    sha256 "01f90930567e1cb283b5d0f1be16e0c2a2ede87a3f32376bbf49549d2d77eaa8"

    def install
      bin.install "linenoise-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/mcornick/linenoise-cli/releases/download/v1.2.15/linenoise-cli_1.2.15_linux_armv7.tar.gz"
      sha256 "0f105fbecb62c4b1be5e33f10830c784ae3cc0cfb4a25cfd7d8620a587f2567a"

      def install
        bin.install "linenoise-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mcornick/linenoise-cli/releases/download/v1.2.15/linenoise-cli_1.2.15_linux_arm64.tar.gz"
      sha256 "40b8df7878bc14f264dd8cc81a95f7a556434e7289f41177280740030c8d9ac6"

      def install
        bin.install "linenoise-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mcornick/linenoise-cli/releases/download/v1.2.15/linenoise-cli_1.2.15_linux_amd64.tar.gz"
      sha256 "2ab95ca0947dd018181d6cdb6bba025968d8e44ddc3a436f2b1816f2838c04e3"

      def install
        bin.install "linenoise-cli"
      end
    end
  end
end
